### ISSUE TITLE
Build fails on windows 10 due to unresolved external symbol _ff_w64_guid_data

### ISSUE THREAD

**Issue by ScriptPup** [jsmarkus/node-webkit-sdk#4]
I'm getting the error mentioned in the title when trying to build. I'm running windows 10, x64, VS 2015... I've found a few mentions to the issue, but didn't see any solutions I could actually implement in my case. The full error stack is below. Hoping someone has an idea, thanks!

`[5962/20899] LINK_EMBED(DLL) ffmpeg.dll
FAILED: ffmpeg.dll ffmpeg.dll.lib ffmpeg.dll.pdb
C:\Dev\depot_tools\python276_bin\python.exe gyp-win-tool link-with-manifests environment.x86 True ffmpeg.dll "C:\Dev\depot_tools\python276_bin\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /IMPLIB:ffmpeg.dll.lib /DLL /OUT:ffmpeg.dll @ffmpeg.dll.rsp" 2 mt.exe rc.exe "obj\third_party\ffmpeg\ffmpeg.ffmpeg.dll.intermediate.manifest" obj\third_party\ffmpeg\ffmpeg.ffmpeg.dll.generated.manifest
ffmpeg.wavdec.obj : error LNK2001: unresolved external symbol _ff_w64_guid_data
ffmpeg.dll : fatal error LNK1120: 1 unresolved externals
Traceback (most recent call last):
  File "gyp-win-tool", line 315, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 171, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "C:\Dev\depot_tools\python276_bin\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Dev\depot_tools\python276_bin\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /IMPLIB:ffmpeg.dll.lib /DLL /OUT:ffmpeg.dll @ffmpeg.dll.rsp ffmpeg.dll.manifest.res' returned non-zero exit status 1120
[5967/20899] CXX obj\third_party\webrtc\modules\audio_processing\audio_processing.gain_control_impl.obj
ninja: build stopped: subcommand failed.`

**Comment by ScriptPup** [comment]
Solution here: https://bugreports.qt.io/browse/QTBUG-54455
Looks like chromium in general has this issue...
